

default:
	##node reader.js // don't continue to build from XML
	##  - we've updated the content in data.json directly and the XML is now out of date soure material
	##  - changes include replacing old broken video links with youtube embeds, and removing a swf that
	##  - we aren't converting.
	npx webpack --config webpack.config.js
